Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('carts', views.carts, name='carts'),
    path('cart/<int:id>/', views.cart_detail, name='cart_detail'),
    path('cart/detail/delete/', views.cart_detail_delete, name='cart_detail_delete'),
    path('wish-list/create', views.create_wish_list, name='create_wish_list'),
    path('wish-list/list', views.list_wish_list, name='list_wish_list'),
    path('wish-list/delete', views.delete_wish_list, name='delete_wish_list'),
    path('profile-edit', views.edit_profile, name='edit_profile'),
    path('set-password', views.set_password, name='set_password'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from functools import reduce
from datetime import datetime


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.SmallIntegerField(
        choices=(
            (1,'Dollar'), 
            (2, 'So`m')
            )
    ) 
    discount_price = models.DecimalField(
        decimal_places=2, 
        max_digits=10, 
        blank=True, 
        null=True
        )
    baner_image = models.ImageField(upload_to='baner/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)


    @property
    def review(self):
        reviews = ProductReview.objects.filter(product_id=self.id)
        result = reduce(lambda result, x: result + x.mark, reviews, 0)
        try:
            result = round(result / reviews.count())
        except ZeroDivisionError:
            result = 0
        return result
    
    @property 
    def is_discount(self):
        if self.discount_price is None:
            return 0
        return self.discount_price > 0
    
    @property 
    def is_active(self):
        return self.quantity > 0


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        # object = WishList.objects.filter(
        #     user=self.user,
        #     product=self.product
        #     )
        # if object.count() == 0:
        #     super(WishList, self).save(*args, **kwargs)
        # else:
        #     raise ValueError
        
        if self.pk:
            print(222)
        else:
            print(111)

        super(WishList, self).save(*args, **kwargs)
    
    def delete(self, *args, **kargs):
        ...
        super(WishList, self).delete(*args, **kargs)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    mark = models.SmallIntegerField()


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    date = models.DateTimeField(blank=True, null=True)

    @property
    def quantity(self):
        quantity = 0
        products = CartProduct.objects.filter(product_id = self.id)
        for i in products:
            quantity +=i.quantity
        return quantity

    @property
    def total_price(self):
        result = 0
        for i in CartProduct.objects.filter(card_id=self.id):
            result +=(i.product.price)*i.quantity
        return result
    
    def save(self, *args, **kwargs):
        if not self.is_active and not self.date:
            self.date = datetime.now()
        super(Cart, self).save(*args, **kwargs)

            
class CartProduct(models.Model):
    card = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    @property
    def total_price(self):
        if self.product.is_discount:
            result = self.product.discount_price * self.quantity
        else:
            result = self.product.price * self.quantity
        return result
    
    @property
    def created_at(self):
        return self.card.date

# cart = Cart.objects.get(id=1)
# details = CartProduct.objects.filter(card=cart)

# for i in details:
#     i.product.quantity -= i.quantity
#     i.product.save()


class EnterProduct(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    product_name = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity}"
    
    def save(self, *args, **kwargs):
        self.product_name = self.product.name
        if self.pk:
            enter = EnterProduct.objects.get(pk=self.pk)
            product = enter.product # None/Product
            product.quantity -= enter.quantity
            product.quantity += self.quantity
            product.save()
        else:
            self.product.quantity += self.quantity
            self.product.save()
        super(EnterProduct, self).save(*args, **kwargs)

main/views.py
from django.shortcuts import render, redirect
from . import models
from django.db.models import Q

def index(request):
    q = request.GET.get('q')
    if q:
        products = models.Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))
    else: 
        products = models.Product.objects.filter(quantity__gt=0)
    categorys = models.Category.objects.all()
    category_id = request.GET.get('category_id')
    if category_id:
        products.filter(category_id=category_id)
    context = {
        'products':products,
        'categorys':categorys
    }
    return render(request, 'index.html', context)


def product_detail(request, id):
    product = models.Product.objects.get(id=id)
    categorys = models.Category.objects.all()
    recomendation = models.Product.objects.filter(
        category_id=product.category.id).exclude(id=product.id)[:3]
    images = models.ProductImage.objects.filter(product_id=product.id)
    is_saved = None
    
    # way 1
    # try:
    #     models.WishList.objects.get(user=request.user, product=product)
    #     is_saved = True
    # except:
    #     is_saved = False

    # way 2
    objects = models.WishList.objects.filter(user=request.user, product=product)
    if objects:
        is_saved = objects.first().id
    else:
        is_saved = False
    print(is_saved)

    # _,b = models.WishList.objects.get_or_create(user=request.user, product=product)
    # a,b = models.WishList.objects.get_or_create(user=request.user, product=product)
    # print(a)
    # print(b)
    context = {
        'product':product,
        'categorys':categorys,
        'recomendation':recomendation,
        'images':images,
        'range':range(product.review), # 0
        'range_passiv':range(5-product.review), # 5
        'is_saved':is_saved
    }
    return render(request, 'product/detail.html', context)


def carts(request):
    active = models.Cart.objects.filter(is_active=True, user=request.user)
    in_active = models.Cart.objects.filter(is_active=False, user=request.user)
    context = {
        'active':active,
        'in_active':in_active
    }
    return render(request, 'cart/carts.html', context)


def cart_detail(request, id):
    cart = models.Cart.objects.get(id=id)
    items = models.CartProduct.objects.filter(card=cart)
    context = {
        'cart':cart,
        'items':items
    }
    return render(request, 'cart/cart_detail.html', context)


def cart_detail_delete(request):
    item_id = request.GET['items_id']
    item = models.CartProduct.objects.get(id=item_id)
    cart_id = item.card.id
    item.delete()
    return redirect('main:cart_detail', cart_id)


def create_wish_list(request):
    # user = request.user
    # product = models.Product.objects.get(id=request.POST['product_id'])
    # models.WishList.objects.create(
    #     user=user,
    #     product=product # obj
    # )
    models.WishList.objects.create(
        user=request.user,
        product_id=request.GET['product_id'] # id
    )
    return redirect('main:index')


def list_wish_list(request):
    objects = models.WishList.objects.filter(user=request.user)
    return render(request, 'wish/list.html', {'objects':objects})


def delete_wish_list(request):
    models.WishList.objects.get(id=request.GET['id']).delete()
    return redirect('main:list_wish_list')



def edit_profile(request):
    if request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['first_name']
        email = request.POST['email']
        user = request.user
        user.username = username
        user.first_name = first_name
        user.email = email
        user.save()
    return render(request, 'profile/edit.html')


def set_password(request):

    old = request.POST['old']
    new = request.POST['new']
    confirm = request.POST['confirm']
    user = request.user
    if user.check_password(old) and new == confirm:
        user.set_password(new)
        user.save()
    return redirect('main:edit_profile')

main/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block content %}

	<!--start-ckeckout-->
	<div class="ckeckout">
		<div class="container">
			<div class="ckeck-top heading">
				<h2>Savatcha</h2>
			</div>
			<div class="ckeckout-top">
			<div class="cart-items">
			 <h3>Savatchadagi masulotlar</h3>
			<div class="in-check" >
				<ul class="unit" style="display: flex;">
					<li><span>Maxsulot</span></li>
					<li><span>Maxsulot soni</span></li>		
					<li><span>Maxsulot narxi</span></li>
					<li><span>Umumiy narx</span></li>
					<li><span>Maxsulot rasmi</span></li>
					<div class="clearfix"> </div>
				</ul>
                {% for i in items %}
				<ul class="cart-header" style="display: flex;">
					<a href="{% url 'main:cart_detail_delete'%}?items_id={{i.id}}"><div class="close1"></div></a>
                    <li><span>{{i.product.name}}</span></li>
                    <li><span>{{i.quantity}}</span></li>
                    <li><span>{{i.product.price}}</span></li>
                    <li><span>{{i.total_price}}</span></li>
                    <li class="ring-in"><a href="#" ><img src="{{ i.product.baner_image.url }}" class="img-responsive" alt="" width="150px"></a>
                    </li>
                    <div class="clearfix"> </div>
				</ul>
                {% endfor %}
			</div>
			</div>  
		 </div>
		</div>
	</div>
	<!--end-ckeckout-->
{% endblock %}

main/templates/cart/carts.html
{% extends 'base.html' %}

{% block content %}

	<!--start-ckeckout-->
	<div class="ckeckout">
		<div class="container">
			<div class="ckeck-top heading">
				<h2>CHECKOUT</h2>
			</div>
			<div class="ckeckout-top">
			<div class="cart-items">
			 <h3>Faol Savatchalar</h3>
			<div class="in-check" >
				<ul class="unit">
					<li><span>Maxsulotlar soni</span></li>
					<li><span>Maxsulotlar narxi</span></li>		
					<div class="clearfix"></div>
				</ul>
                {% for cart in active %}
				<ul class="cart-header">
						<li><span class="name">{{cart.quantity}}</span></li>
						<li><span class="cost">{{cart.total_price}}</span></li>
					<div class="clearfix"> </div>
				</ul>
                {% endfor %}
			</div>
			 <h3>Nofaol Savatchalar</h3>
			<div class="in-check" >
				<ul class="unit">
					<li><span>Maxsulotlar soni</span></li>
					<li><span>Maxsulotlar narxi</span></li>		
					<div class="clearfix"></div>
				</ul>
                {% for cart in in_active %}
				<ul class="cart-header">
						<li><span class="name">{{cart.quantity}}</span></li>
						<li><span class="cost">{{cart.total_price}}</span></li>
					<div class="clearfix"> </div>
				</ul>
                {% endfor %}
			</div>
			</div>  
		 </div>
		</div>
	</div>
	<!--end-ckeckout-->
{% endblock %}