Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard),
    path('product-list', views.products),
    path('product-create', views.product_create),
    path('product-detail/<int:id>/', views.product_detail, name='product_detail'),
    # enters
    path('enter-list', views.list_enter, name='list_enter'),
    path('enter-create', views.create_enter, name='create_enter'),
    path('enter-update/<int:id>/', views.update_enter, name='update_enter'),
    path('enter-delete/<int:id>/', views.delete_enter, name='delete_enter'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('carts', views.carts, name='carts'),
    path('cart/<int:id>/', views.cart_detail, name='cart_detail'),
    path('cart/detail/delete/', views.cart_detail_delete, name='cart_detail_delete'),
    path('wish-list/create', views.create_wish_list, name='create_wish_list'),
    path('wish-list/list', views.list_wish_list, name='list_wish_list'),
    path('wish-list/delete', views.delete_wish_list, name='delete_wish_list'),
    path('profile-edit', views.edit_profile, name='edit_profile'),
    path('set-password', views.set_password, name='set_password'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from itertools import chain

from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.core.exceptions import FieldError

from main import models
from . funcs import search_with_fields, pagenator_page



def dashboard(request):
    categorys = models.Category.objects.all().count()
    products = models.Product.objects.all().count()
    users = User.objects.all().count()
    context = {
        'categorys':categorys,
        'products':products,
        'users':users,
    }
    return render(request, 'dashboard/index.html', context)


def category_list(request):
    categorys = models.Category.objects.all()
    return render(request, 'category/list.html', {'categorys':categorys})


def category_detail(request, id):
    category = models.Category.objects.get(id=id)
    products = models.Product.objects.filter(category=category, is_active=True)
    context = {
        'category':category,
        'products':products
    }
    return render(request, 'category/list.html', context)


def category_update(request, id):
    category = models.Category.objects.get(id=id)
    category.name = request.POST['name']
    category.save()
    return redirect('category_detail', category.id)


def category_delete(request, id):
    category = models.Category.objects.get(id=id)
    category.delete()
    return redirect('category_list')




# products

def products(request):
    products = models.Product.objects.all()
    return render(request, 'dashboard/products/list.html', {'products':products})


def product_create(request):
    categorys = models.Category.objects.all()
    context = {
        'categorys':categorys
    }
    if request.method == "POST":
        name = request.POST['name']
        description = request.POST['description']
        quantity = request.POST['quantity']
        price = request.POST['price']
        currency = request.POST['currency']
        baner_image = request.FILES['baner_image']
        category_id = request.POST['category_id']
        images = request.FILES.getlist('images')
        product = models.Product.objects.create(
            name=name,
            description = description,
            quantity=quantity,
            price=price,
            currency=currency,
            baner_image=baner_image,
            category_id=category_id
        )
        for image in images:
            models.ProductImage.objects.create(
                image=image,
                product=product
            )

    return render(request, 'dashboard/products/create.html', context)


def product_detail(request, id):
    product = models.Product.objects.get(id=id)
    enters = models.EnterProduct.objects.filter(product=product)
    outs = models.CartProduct.objects.filter(product=product, card__is_active=False)
    query_set = sorted(
        chain(
            enters,
            outs
        ),
        key = lambda x : x.created_at
    )
    # for i in query_set:
    #     try:
    #         i.card
    #         print(f"chiqish {i}")
    #     except:
    #         print(f"kirish {i}")

    return render(request, 'dashboard/products/detail.html', {'query_set':query_set})

def create_enter(request):
    if request.method == 'POST':
        product_id = request.POST['product_id']
        quantity = int(request.POST['quantity'])
        models.EnterProduct.objects.create(
            product_id=product_id,
            quantity=quantity
        )
        return redirect('dashboard:list_enter')
    return render(request, 'dashboard/enter/create.html', {'products':models.Product.objects.all()})


def update_enter(request, id):
    if request.method == 'POST':
        quantity = int(request.POST['quantity'])
        enter = models.EnterProduct.objects.get(id=id)
        enter.quantity = quantity
        enter.save()
    return redirect('dashboard:list_enter')


def delete_enter(request, id):
    models.EnterProduct.objects.get(id=id).delete()
    return redirect('dashboard:list_enter')



def list_enter(request):
    result = search_with_fields(request)
    try: 
        enters = models.EnterProduct.objects.filter(**result)

    except FieldError as err:
        del result[err.__doc__.split()[3][1:-1]]
        enters = models.EnterProduct.objects.filter(**result)

    context = {'enters': pagenator_page(enters, 1, request)}
    return render(request, 'dashboard/enter/list.html', context)

# required
# def list_enter(request):
#     name = request.GET.get('name')
#     quantity = request.GET.get('quantity')
#     created_at = request.GET.get('created_at')
#     if name and quantity and created_at:
#         enters = models.EnterProduct.objects.filter(
#             product__name=name,
#             quantity=quantity,
#             created_at__gt = created_at,
#             created_at__lte = created_at,
#         )
#     else:
#         enters = models.EnterProduct.objects.all()
#     context = {'enters':enters}
#     return render(request, 'dashboard/enter/list.html', context)


def product(request):
    
      if request.method == 'GET':
        result = search_with_fields(request)
        enters = models.Product.objects.filter(**result)
        context = {'name': pagenator_page(name, 1, request)}

        return render(request, 'dashboard/product/list.html')

dashboard/templates/dashboard/enter/create.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<!--app-content open-->
       <div class="main-content app-content mt-0">
        <div class="side-app">

            <!-- CONTAINER -->
            <div class="main-container container-fluid">

                <!-- PAGE-HEADER -->
                <div class="page-header">
                    <h1 class="page-title">Maxsulot</h1>
                </div>
                <!-- PAGE-HEADER END -->
                
                <!-- Row -->
                <div class="row">
                    <div class='col-3'></div>
                    <div class="col-xl-6 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Maxsulotga kirim qilish</h3>
                            </div>
                            <form method='post' enctype="multipart/form-data"> 
                                {% csrf_token %} 
                            <div class="card-body pb-2">
                                <div class="row row-sm">
                                    <div class="form-group">
                                        <label>Maxsulotlar</label>
                                        <select class="form-control select2" name="product_id">
                                        {% for product in products %}
                                        <option value="{{product.id}}">{{product.name}}</option>
                                        {% endfor %}
                                    </select>
                                        <label>Miqdor</label>
                                        <input class="form-control mb-4" required type="number" name="quantity">
                                        </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-9"></div>
                                    <div class="col">
                                        <button class='btn btn-default btn-pill'>Yaratish</button>  
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
                <!-- End Row -->

            </div>
            <!-- CONTAINER CLOSED -->

        </div>
    </div>
    <!--app-content close-->
    {% endblock %}


{% block js %}
<!-- FILE UPLOADES JS -->
   <script src="{% static 'dashboard/plugins/fileuploads/js/fileupload.js' %}"></script>
   <script src="{% static 'dashboard/plugins/fileuploads/js/file-upload.js' %}"></script>

   <!-- INTERNAL File-Uploads Js-->
   <script src="{% static 'dashboard/plugins/fancyuploder/jquery.ui.widget.js' %}"></script>
   <script src="{% static 'dashboard/plugins/fancyuploder/jquery.fileupload.js' %}"></script>
   <script src="{% static 'dashboard/plugins/fancyuploder/jquery.iframe-transport.js' %}"></script>
   <script src="{% static 'dashboard/plugins/fancyuploder/jquery.fancy-fileupload.js' %}"></script>
   <script src="{% static 'dashboard/plugins/fancyuploder/fancy-uploader.js' %}"></script>
{% endblock %}

dashboard/templates/dashboard/enter/list.html
{% extends 'dashboard/base.html' %}
{% block content %}
<!--app-content open-->
    <div class="main-content app-content mt-0">
        <div class="side-app">

            <!-- CONTAINER -->
            <div class="main-container container-fluid">

                <!-- PAGE-HEADER -->
                <!-- <div class="page-header">
                        <form method="get" class="d-flex">
                            <label for="name">Maxsulot nom</label>
                            <input class="form-control" type="text" name="name" id="name" required>
                            <label for="quantity">Miqdor</label>
                            <input class="form-control" type="number" name="quantity" id="quantity" required>
                            <label for="created_at">Sana</label>
                            <input class="form-control" type="datetime-local" name="created_at" id="created_at" required>
                            <button type="submit" class="btn btn-success w-50 ms-1" >Filter</button>
                        </form>
                    <button class="btn btn-primary">Excel generate</button>
                </div> -->
                <div class="page-header">
                        <form method="get" class="d-flex">
                            <label for="name">Maxsulot nom</label>
                            <input class="form-control" type="text" name="name" id="name">
                            <label for="quantity">Miqdor</label>
                            <input class="form-control" type="number" name="quantity" id="quantity">
                            <label for="created_at_start">Sana Boshlanish</label>
                            <input class="form-control" type="datetime-local" name="created_at_start" id="created_at_start">
                            <label for="created_at_end">Sana Tugash</label>
                            <input class="form-control" type="datetime-local" name="created_at_end" id="created_at_end">
                            <button type="submit" class="btn btn-success w-50 ms-1" >Filter</button>
                        </form>
                    <!-- <button class="btn btn-primary">Excel generate</button> -->
                </div>
                <!-- PAGE-HEADER END -->
                
                <!-- Row -->
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-xl-8">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kirimlar ro`yxati</h3>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table text-nowrap text-md-nowrap mb-0">
                                        <thead>
                                            <tr>
                                                <th>№</th>
                                                <th>Maxsulot nomi</th>
                                                <th>Soni</th>
                                                <th>Sana</th>
                                                <th>O`zgartirish</th>
                                                <th>O`chirish</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for enter in enters %}
                                            <tr>
                                                <td>{{forloop.counter}}</td>
                                                {% if enter.product %}
                                                <td>{{enter.product.name}}</td>
                                                {% else %}
                                                <td>{{enter.product_name}}</td>
                                                {% endif %}
                                                <td>{{enter.quantity}}</td>
                                                <td>{{enter.created_at|date:'Y-m-d H:i'}}</td>
                                                {% if enter.product %}
                                                <td><button data-bs-target="#modalupdate{{enter.id}}" data-bs-toggle="modal" href="javascript:void(0)" class="btn btn-success">O'zgartirish</button></td>
                                                {% else %}
                                                <td><button class="btn btn-success">O'zgartirish</button></td>
                                                {% endif %}
                                                <td><button data-bs-target="#modaldelete{{enter.id}}" data-bs-toggle="modal" href="javascript:void(0)" class="btn btn-danger">O'chirish</button></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <br>
                                <div class="d-flex justify-content-end" >
                                    
                                    <!-- <ul class="pagination">
                                        <li class="page-item page-prev">
                                            <a class="page-link" href="javascript:void(0)" tabindex="-1">Prev</a>
                                        </li>
                                        <li class="page-item active"><a class="page-link" href="javascript:void(0)">1</a></li>
                                        <li class="page-item"><a class="page-link" href="javascript:void(0)">2</a></li>
                                        <li class="page-item"><a class="page-link" href="javascript:void(0)">3</a></li>
                                        <li class="page-item"><a class="page-link" href="javascript:void(0)">4</a></li>
                                        <li class="page-item page-next">
                                            <a class="page-link" href="javascript:void(0)">Next</a>
                                        </li>
                                    </ul> -->
                                    <div class="col-12 text-right">
                                        {% if enters.paginator.num_pages > 1 %}
                                            <nav aria-label="Page navigation example" class="text-end">
                                                <ul class="pagination">
                                                    {% if enters.has_previous %}
                                                    <li class="page-item page-prev"><a class="page-link" href="?page={{ enters.previous_page_number  }}"><<</a></li>
                                                    {% endif %}
                                                    {% for num in enters.paginator.page_range %}
                                                    {% if num == enters.number %}
                                                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                                                    {% elif num > enters.number|add:'-3' and num < enters.number|add:'3' %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                    {% endif %}
                                                    {% endfor %}
                                                    {% if enters.has_next %}
                                                    <li class="page-item page-next"><a class="page-link" href="?page={{ enters.next_page_number }}">>></a></li>
                                                    {% endif %}
                                                </ul>
                                            </nav>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Row -->
                {% for i in enters %}
                <div class="modal fade" id="modalupdate{{i.id}}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content modal-content-demo">
                            <div class="modal-header">
                                <h6 class="modal-title">Kirimni o`zgartirish</h6><button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">
                                <form action="{% url 'dashboard:update_enter' i.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="text" class="form-control" name="quantity" value="{{i.quantity}}">
                                
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-primary" type="submit">Saqlash</button> 
                                <button class="btn btn-light" data-bs-dismiss="modal">Qaytish</button>
                            </form>    
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="modaldelete{{i.id}}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content modal-content-demo">
                            <div class="modal-header">
                                <h6 class="modal-title">Maxsulotni o`chriish</h6><button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">
                                <form action="{% url 'dashboard:delete_enter' i.id %}" method="get">
                                    <label for="my_chkb">O`chirmoqchimisiz? </label>
                                    <input type="checkbox" required id="my_chkb">
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-primary" type="submit">O`chrish</button> 
                                    <button class="btn btn-light" data-bs-dismiss="modal">Close</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- CONTAINER CLOSED -->

        </div>
    </div>
    <!--app-content close-->
    {% endblock %}